### PR TITLE
Add bed command

### PR DESCRIPTION
**Pull request by floppydisk05**
I bet this is half broken lmao

### CODE REVIEW

**Comment by Starman0620** [comment]
a

**Comment by floppydisk05** [comment]
w h y

**Comment by floppydisk05** [comment]
image

**Comment by floppydisk05** [comment]
image

**Comment by Starman0620** [comment]
It's
a

**Comment by floppydisk05** [comment]
whatswrong
image

**Comment by Starman0620** [comment]
a

**Comment by floppydisk05** [comment]
why fhsdkghldfgldsfgkdsnfgkdngdsnfgkdsng

**Comment by floppydisk05** [comment]
tellmeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Starman0620** [comment]
a

**Comment by floppydisk05** [comment]
why

**Comment by Starman0620** [comment]
a

**Comment by floppydisk05** [comment]
not until you tell me whats worong with it

**Comment by nick99nack** [comment]
floppy go the fuck to bed

**Comment by floppydisk05** [comment]
image

**Comment by nick99nack** [comment]
I have to write a better bed command dammit

**Comment by floppydisk05** [comment]
thendoitfaster

**Comment by floppydisk05** [comment]
alsowhatswrongwithmine

**Comment by Starman0620** [comment]
> I have to write a better bed command dammit

a

**Comment by floppydisk05** [comment]
image
image

**Comment by floppydisk05** [comment]
tellmewhatswrongaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by nick99nack** [comment]
no

**Comment by floppydisk05** [comment]
image

**Comment by nick99nack** [comment]
floppy go to bed or I ban your ass for 30 days

**Comment by Starman0620** [comment]
nick btw yours will probably have the same issue as this one but I'll tell you when it happens

**Comment by floppydisk05** [comment]
image

**Comment by nick99nack** [comment]
lol k

**Comment by floppydisk05** [comment]
I read ban as bet send help

**Comment by floppydisk05** [comment]
long pull request

**Comment by nick99nack** [comment]
honestly you could use floppy's for right now because my idea is different than what's being done here lol

**Comment by Starman0620** [comment]
I wont though. It has an issue

**Comment by floppydisk05** [comment]
whatisit

**Comment by Starman0620** [comment]
I dunno. You tell me?

**Comment by floppydisk05** [comment]
what

**Comment by floppydisk05** [comment]
it has an issue which you know about and oyu won't tell me

**Comment by Starman0620** [comment]
Actually...

**Comment by Starman0620** [comment]
There's two. One more minor tho

**Comment by floppydisk05** [comment]
*streeettcchh*

/ᐠ-ꞈ-ᐟ\
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█_∫

**Comment by floppydisk05** [comment]
whatarethey

**Comment by floppydisk05** [comment]
tellmenow

**Comment by floppydisk05** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by floppydisk05** [comment]
f in e

**Comment by floppydisk05** [comment]
godnignt jfk sdafsfksgdjfshdaf ky839p5;.k,3

**Pull request closed without merging**
