### PR TITLE
Added floppydisk to about command

### PR DESCRIPTION
**Pull request by floppydisk05**
Technically I'm a contributor too smh
norton

### CODE REVIEW

**Comment by Starman0620** [comment]
Smh smh not for V3

**Comment by floppydisk05** [comment]
bruh

**Comment by floppydisk05** [comment]
99% of the code for the rory command I added is the same tho lmao

**Comment by floppydisk05** [comment]
the only parts that have actually changed are the parts which needed to be changed for DSharpPlus :norton:

**Comment by floppydisk05** [comment]
Cmon goddamit just accept it. I want to remove this repo from my profile lol. too much c l u t t e r

**Comment by xproot** [comment]
m

**Pull request closed without merging**
